### ISSUE TITLE
Principais pesquisadores

### ISSUE THREAD

**Issue by Carlos-Henreis** [gazzola/AprendizagemProfunda-Curso-DeepLearning-Course#1]
Primeiramente queria agradecer pela suas contribuições :+1: , me ajudou muito em minhas pesquisas.
Só tenho um questionamento: Acho que vc esqueceu de citar pesquisadores importantes na seção de "Principais pesquisadores".
Aqui estão alguns figuras que considero importantíssimos para área de Deep Learning:

- [Martin Abadi](https://scholar.google.com/citations?user=vWTI60AAAAAJ&hl=en)

- [Ian Goodfellow](https://scholar.google.ca/citations?user=iYN86KEAAAAJ&hl=en)

- [Christopher Olah](http://colah.github.io)

ps: É apenas uma sugestão.

Novamente, parabéns pelo trabalho

**Comment by gazzola** [comment]
@Carlos-Henreis muito obrigado pela indicação. Já adicionei na lista, só não está ordenada ainda de A-Z. Também fico muito feliz que ajudou no seu trabalho,  a ideia foi esta mesmo.
**Abraços**
